// This file was automatically generated by lister-gen

package v1alpha1

// MemcachedListerExpansion allows custom methods to be added to
// MemcachedLister.
type MemcachedListerExpansion interface{}

// MemcachedNamespaceListerExpansion allows custom methods to be added to
// MemcachedNamespaceLister.
type MemcachedNamespaceListerExpansion interface{}
